project:
  type: website

website:
  title: "wiki"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CHANGELOG.md
  favicon: images/favicon.ico
  sidebar: 
    contents:
    - href: index.qmd
      text: "🏠 Home"
    - href: CHANGELOG.md
      text: "❗ CHANGELOG"
    - href: ProjectManagement/Plagiat.md
      text: "Plagiat and LLM"
    - section: "🎞 Pandora"
      contents:
        - href: Pandora/Pandora.md
          text: "Manual page"
        - href: Pandora/Features.md
          text: "Features"
        - href: Pandora/Constants.md
          text: "Constants"
        - href: Pandora/Flight-Records.md
          text: "Flight Records"
        - href: Pandora/Flight-Phases.md
          text: "Flight Phases"
        - href: Pandora/Error-Handling.md
          text: "Error Handling"
        - href: Resources/CLI.md
          text: "CLI Reference"
        - href: ProjectManagement/manifest.json.md
          text: "manifest.json"
    - section: "🔧 Building the Project"
      contents:
        - href: tools/maven.md
          text: "Maven"
        - href: tools/vscode.md
          text: "VS Code"
        - href: tools/Eclipse.md
          text: "Eclipse"

    - section: "Project Management"
      contents:
        - section: "<b>Test-Driven-Development</b>"
          contents:
            - href: ProjectManagement/TestDrivenDevelopment/Test-Driven-Development.md
              text: "What is Test-Driven Development?"
            - href: ProjectManagement/TestDrivenDevelopment/Unit-Test.md
              text: "Unit Tests"
            - href: ProjectManagement/TestDrivenDevelopment/Integration-Test.md
              text: "Integration Tests"
            - href: ProjectManagement/TestDrivenDevelopment/TestSuite.md
              text: "TestSuite & Autograder"
            - href: ProjectManagement/TestDrivenDevelopment/Code-Coverage.md
              text: "Code Coverage"
        - section: "Versioning and Releasing"
          contents:
          - href: ProjectManagement/Versioning/Conventional-Commits.md
            text: "Conventional Commits"
          - href: ProjectManagement/Versioning/Semantic-Versioning.md
            text: "Semantic Versioning"
          - href: ProjectManagement/Versioning/Release.md
            text: "Release"
          - href: ProjectManagement/Versioning/Keep-A-Changelog.md
            text: "Keep a Changelog"
          - href: ProjectManagement/Versioning/Git-Clients.md
            text: "Git Clients"
          - href: ProjectManagement/Versioning/Configuration-git.md
            text: "Git User Configuration"
        - section: "Other"
          contents:
          - href: ProjectManagement/Javadoc.md
            text: "Javadoc"
          - href: ProjectManagement/File Management.md
            text: "File Management"
          - href: ProjectManagement/Issues.md
            text: "Issues"
          - href: ProjectManagement/Debug.md
            text: "Debug"
          - href: ProjectManagement/Synchronize-Update-From-The-Starterpack.md
            text: "❗ Sync from Starterpack"

  

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



metadata-files:
  - ./_sidebar.yml

